Fix maxpk breaking when Model default order_by
When we set a order_by close in a model Meta, this order_by is used
and which does not make psql happy:

    peewee.ProgrammingError: column "t1.number" must appear in the
    GROUP BY clause or be used in an aggregate function